### ISSUE TITLE
PDB: Cannot parse DeviceSQL string

### ISSUE THREAD

**Issue by Holzhaus** [Holzhaus/rekordcrate#76]
I'm seeing this error when trying to parse the `export.pdb` file from https://github.com/mixxxdj/mixxx/issues/10923#issuecomment-1261216718.

```
Table 3: Albums
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:
 ╺━━━━━━━━━━━━━━━━━━━━┅ Backtrace ┅━━━━━━━━━━━━━━━━━━━━╸

 0: Error: no variants matched at 0x8f10...
   ╭───────────────────────┄ Album ┄────────────────────┄
   ┆
   ┆ 0: Error: no variants matched at 0x8f25...
   ┆   ╭───────────────────────┄ ShortASCII ┄────────────────────┄
   ┆   ┆
   ┆   ┆header & 0b1 == 1 at 0x8f25
   ┆   ╰─────────────────────────────────────────────────────────┄
   ┆   ╭───────────────────────┄ Long ┄────────────────────┄
   ┆   ┆
   ┆   ┆bad magic at 0x8f28: 111
   ┆   ╰───────────────────────────────────────────────────┄
   ┆    ...While parsing field 'self_0' in DeviceSQLString
   ┆     at src/pdb/string.rs:54
   ┆ 1: While parsing field 'name' in Album
   ┆     at src/pdb/mod.rs:432
   ┆ 2: While parsing field 'self_0' in Row::Album
   ┆     at src/pdb/mod.rs:821
   ┆
   ╰────────────────────────────────────────────────────┄
   ```

**Comment by Swiftb0y** [comment]
I can look into this tomorrow.
